// <auto-generated />
using System;
using BenhVienThongNhat_DangKy.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BenhVienThongNhat_DangKy.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    partial class DataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("BenhVienThongNhat_DangKy.Models.BenhNhan", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("hoten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("id_gioitinh")
                        .HasColumnType("int");

                    b.Property<int>("id_phong")
                        .HasColumnType("int");

                    b.Property<string>("mabn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("namsinh")
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("sothe")
                        .HasColumnType("text");

                    b.Property<DateTime>("thoigian")
                        .HasColumnType("datetime");

                    b.HasKey("id");

                    b.HasIndex("id_gioitinh");

                    b.HasIndex("id_phong");

                    b.ToTable("BenhNhan");
                });

            modelBuilder.Entity("BenhVienThongNhat_DangKy.Models.GioiTinh", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("GioiTinh");
                });

            modelBuilder.Entity("BenhVienThongNhat_DangKy.Models.Khoa", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("id_khu")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("id_khu");

                    b.ToTable("Khoa");
                });

            modelBuilder.Entity("BenhVienThongNhat_DangKy.Models.Khu", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Khu");
                });

            modelBuilder.Entity("BenhVienThongNhat_DangKy.Models.phong", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("id_khoa")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("sceensize")
                        .HasColumnType("text");

                    b.Property<string>("scrolltime")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("id_khoa");

                    b.ToTable("Phong");
                });

            modelBuilder.Entity("BenhVienThongNhat_DangKy.Models.BenhNhan", b =>
                {
                    b.HasOne("BenhVienThongNhat_DangKy.Models.GioiTinh", "gioiTinh")
                        .WithMany("thongTinKhamBenh")
                        .HasForeignKey("id_gioitinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BenhVienThongNhat_DangKy.Models.phong", "phong")
                        .WithMany("thongTinKhamBenh")
                        .HasForeignKey("id_phong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("gioiTinh");

                    b.Navigation("phong");
                });

            modelBuilder.Entity("BenhVienThongNhat_DangKy.Models.Khoa", b =>
                {
                    b.HasOne("BenhVienThongNhat_DangKy.Models.Khu", "khu")
                        .WithMany("khoa")
                        .HasForeignKey("id_khu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("khu");
                });

            modelBuilder.Entity("BenhVienThongNhat_DangKy.Models.phong", b =>
                {
                    b.HasOne("BenhVienThongNhat_DangKy.Models.Khoa", "khoa")
                        .WithMany("phong")
                        .HasForeignKey("id_khoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("khoa");
                });

            modelBuilder.Entity("BenhVienThongNhat_DangKy.Models.GioiTinh", b =>
                {
                    b.Navigation("thongTinKhamBenh");
                });

            modelBuilder.Entity("BenhVienThongNhat_DangKy.Models.Khoa", b =>
                {
                    b.Navigation("phong");
                });

            modelBuilder.Entity("BenhVienThongNhat_DangKy.Models.Khu", b =>
                {
                    b.Navigation("khoa");
                });

            modelBuilder.Entity("BenhVienThongNhat_DangKy.Models.phong", b =>
                {
                    b.Navigation("thongTinKhamBenh");
                });
#pragma warning restore 612, 618
        }
    }
}
